### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by mathieuleclaire** [plasmap/pamphlet#2]
Hi,
I have an error compiling the example of the README at this line:
```scala
val leafletMap = Leaflet.map(cssId, conf).setView(scalajs.js.Array(51.505f, -0.09f), 13)
```
It seems the API changed and a LeafletLatLng is expected rather than a js.Array.

Thanks

**Comment by janschultecom** [comment]
I updated the doc. Try this: 
```scala
leafletMap.setView(Leaflet.latLng(x, y), z)
```
