### ISSUE TITLE
Mapbox server unreahable

### ISSUE THREAD

**Issue by mathieuleclaire** [plasmap/pamphlet#4]
Hi,
when trying to execute the example script, an error 401 is sent:
```sh
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

Should I need an account on mapbox ?
Thanks
Mathieu

**Comment by janschultecom** [comment]
Yes! Alternatively you can use cartodb, which doesn't require an account:
https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png

**Comment by mathieuleclaire** [comment]
OK, It works ! Thanks for this work !
